import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [productImage, setProductImage] = useState('');
	const [uploadData, setUploadData] = useState();

	const handleUploadImage = (changeEvent) => {
		// setProductImage(e.target.value);
		// console.log(e.target.files);

		const reader = new FileReader();
		reader.onload = (onLoadEvent) => {
			console.log(onLoadEvent);
			console.log(onLoadEvent.target.result);
			// setProductImage(onLoadEvent.target.result);
			setUploadData(undefined);
		};

		reader.readAsDataURL(changeEvent.target.files[0]);
	};

	const handleSubmitImage = async (e) => {
		e.preventDefault();

		const form = e.currentTarget;
		console.log(form);

		const fileInput = Array.from(form.elements).find(
			({ name }) => name === 'file'
		);
		console.log('fileInput', fileInput);
		console.log('fileInput.files', fileInput.files);

		const formData = new FormData();

		for (const file of fileInput.files) {
			console.log(file);
			console.log(file.name);
			formData.append('file', file);
		}
		formData.append('upload_preset', 'product-images');

		console.log(formData);

		const data = await fetch(
			'https://api.cloudinary.com/v1_1/dkclcbezp/image/upload',
			{
				method: 'POST',
				body: formData
			}
		).then((r) => r.json());

		data && console.log(data);
		setProductImage(data.secure_url);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto">
				<p className="text-4xl text-center m-20">Cloudinary Upload + Fetch</p>
			</div>
			<div>
				<form
					method="post"
					// onChange={handleUploadImage}
					onSubmit={handleSubmitImage}
				>
					<label
						className="text-center block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
						htmlFor="file_input"
					>
						Upload Image
					</label>
					<input
						onChange={handleUploadImage}
						// className="block w-60 mx-auto text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
						// aria-describedby="file_input_help"
						// id="file_input"
						name="file"
						type="file"
						// value={productImage}
					/>
					{/* <br /> */}
					{/* <div className="mx-auto justify-center text-center"> */}
					{/* {productImage && !uploadData && ( */}
					<button className="inline-flex mx-auto float-center w-full justify-center rounded-md border border-transparent bg-gray-900 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-gray-700 dark:hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm">
						Upload
					</button>
					{/* )} */}

					{/* </div> */}
				</form>
			</div>
			<br />
			{productImage && (
				<Image width={500} height={500} alt="productImage" src={productImage} />
			)}
		</div>
	);
}
